/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat.food;

import java.util.List;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.JTableBinding.ColumnBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author Laboratorio
 */
public class JanelaListagemPedidos extends javax.swing.JFrame {

    private List<Pedido> pedidos;
    private Restaurante res = Login.getInstance();
    
    /**
     * Creates new form JanelaListagemPedidos
     */
    public JanelaListagemPedidos() {
        PedidoDAO pedidoDao = new PedidoDAO();
        
        pedidos = new LinkedList<>();
        pedidos = pedidoDao.listarPorRestaurante(Login.getInstance());
        initComponents();
        
        BindingGroup bg = new BindingGroup();
        JTableBinding tb = SwingBindings.createJTableBinding(
            AutoBinding.UpdateStrategy.READ_WRITE,
            pedidos,
            tbPedidos
        );
        ColumnBinding cb = tb.addColumnBinding(
            BeanProperty.create("id_pedido")
        );
        cb.setColumnName("ID");
        cb.setColumnClass(Integer.class);
        
        cb = tb.addColumnBinding(BeanProperty.create("descricao"));
        cb.setColumnName("Descrição");
        cb.setColumnClass(String.class);
        
        cb = tb.addColumnBinding(BeanProperty.create("valor_total"));
        cb.setColumnName("Valor Total");
        cb.setColumnClass(Double.class);
        
        cb = tb.addColumnBinding(BeanProperty.create("status"));
        cb.setColumnName("Status");
        cb.setColumnClass(String.class);
        
        bg.addBinding(tb);
        
        bg.bind();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        detailsButton = new javax.swing.JButton();
        btVisualizarCardapio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ListaPedidos = new javax.swing.JScrollPane();
        tbPedidos = new javax.swing.JTable();
        prpbtn = new javax.swing.JButton();
        fnzbtn = new javax.swing.JButton();
        entbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listagem de Pedidos");

        confirmButton.setText("Confirmar");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmButton);

        detailsButton.setText("Detalhes");
        detailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(detailsButton);

        btVisualizarCardapio.setText("Visualizar Cardápio");
        btVisualizarCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarCardapioActionPerformed(evt);
            }
        });
        jPanel1.add(btVisualizarCardapio);
        jPanel1.add(jSeparator1);

        tbPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ListaPedidos.setViewportView(tbPedidos);

        prpbtn.setText("Preparando");
        prpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prpbtnActionPerformed(evt);
            }
        });

        fnzbtn.setText("Finalizado");
        fnzbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnzbtnActionPerformed(evt);
            }
        });

        entbtn.setText("Entregue");
        entbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ListaPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(prpbtn)
                .addGap(18, 18, 18)
                .addComponent(fnzbtn)
                .addGap(25, 25, 25)
                .addComponent(entbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ListaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prpbtn)
                    .addComponent(fnzbtn)
                    .addComponent(entbtn))
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsButtonActionPerformed
        if(tbPedidos.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(
                rootPane, 
                "Selecione um pedido"
            );
        } else if (tbPedidos.getSelectedRows().length > 1) {
            JOptionPane.showMessageDialog(
                rootPane, 
                "Selecione apenas um pedido!"
            );
        } else {
            int linha = tbPedidos.getSelectedRow();
            int idxLista = tbPedidos.convertRowIndexToModel(linha);
            
            Pedido pedidoSelecionado = pedidos.get(idxLista);
            
            TelaDetalhesPedido tdp = new TelaDetalhesPedido(pedidoSelecionado);
            tdp.setVisible(true);
            
            
        }
    }//GEN-LAST:event_detailsButtonActionPerformed

    private void btVisualizarCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarCardapioActionPerformed
        
        new ListagemCardapio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVisualizarCardapioActionPerformed

    private void prpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prpbtnActionPerformed
       if (tbPedidos.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um pedido!");
        } else if (tbPedidos.getSelectedRows().length > 1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione apenas um pedido!");
        } else {
            int linha = tbPedidos.getSelectedRow();
            int idxLista = tbPedidos.convertRowIndexToModel(linha);
            
            Pedido pedidoSelecionado = pedidos.get(idxLista);
            pedidoSelecionado.setStatus("Preparando");
            Pedido p = new Pedido();
            
            p.setId_pedido(pedidoSelecionado.getId_pedido());
            p.setRestaurante(res);
            p.setCliente(pedidoSelecionado.getCliente());
            p.setDescricao(pedidoSelecionado.getDescricao());
            p.setHorario_pedido(pedidoSelecionado.getHorario_pedido());
            p.setStatus(pedidoSelecionado.getStatus());
            p.setValor_total(pedidoSelecionado.getValor_total());
            p.setEndereco(pedidoSelecionado.getEndereco());
            
                     
            PedidoDAO pd = new PedidoDAO();
            
            try{ 
                pd.alterar(p);
            } catch(Exception e) {
                e.printStackTrace();
            }
            
            
            
        }
    }//GEN-LAST:event_prpbtnActionPerformed

    private void fnzbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnzbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnzbtnActionPerformed

    private void entbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entbtnActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaListagemPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaListagemPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaListagemPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaListagemPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaListagemPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ListaPedidos;
    private javax.swing.JButton btVisualizarCardapio;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton detailsButton;
    private javax.swing.JButton entbtn;
    private javax.swing.JButton fnzbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton prpbtn;
    private javax.swing.JTable tbPedidos;
    // End of variables declaration//GEN-END:variables
}
