/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat.food;

import java.util.List;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.JTableBinding.ColumnBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author Laboratorio
 */
public class ListagemCardapio extends javax.swing.JFrame {
    public BindingGroup bg;
    public List<ItemCardapio> lstItemCardapio;
    public Cardapio cardapio;
    
    /**
     * Creates new form ListagemCardapio
     */
    public ListagemCardapio() {
        initComponents();
        listCardapio();
        initBindings();
    }
    
    public void listCardapio() {
        CardapioDAO cd = new CardapioDAO();
        ItemDAO id = new ItemDAO();
        
        cardapio = cd.consultarPorRestaurante(Login.getInstance());
    
        if (cardapio == null) {
            cardapio = new Cardapio();
            cardapio.setRestaurante(Login.getInstance());
            cd.inserir(cardapio);
        }
        
        lstItemCardapio = id.listarPorCardapio(cardapio);
    }
    
    public void initBindings() {
        if (bg != null) {
            bg.unbind();
        }
        
        bg = new BindingGroup();
        
        JTableBinding tb = SwingBindings.createJTableBinding(
            AutoBinding.UpdateStrategy.READ_WRITE,
            lstItemCardapio,
            tbItemCardapio
        );

        ColumnBinding cb = tb.addColumnBinding(BeanProperty.create("nome"));
        cb.setColumnName("Nome");
        cb.setColumnClass(String.class);

        cb = tb.addColumnBinding(BeanProperty.create("preco"));
        cb.setColumnName("Preço");
        cb.setColumnClass(Float.class);
        
        cb = tb.addColumnBinding(BeanProperty.create("descricao"));
        cb.setColumnName("Descrição");
        cb.setColumnClass(String.class);

        bg.addBinding(tb);
        
        bg.bind();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spItensCardapio = new javax.swing.JScrollPane();
        tbItemCardapio = new javax.swing.JTable();
        pnBotoes = new javax.swing.JPanel();
        btListagemPedidos = new javax.swing.JButton();
        btAdicionar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listagem Cardápio");

        tbItemCardapio.setAutoCreateRowSorter(true);
        tbItemCardapio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spItensCardapio.setViewportView(tbItemCardapio);

        btListagemPedidos.setText("Listagem dos Pedidos");
        btListagemPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListagemPedidosActionPerformed(evt);
            }
        });
        pnBotoes.add(btListagemPedidos);

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        pnBotoes.add(btAdicionar);

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        pnBotoes.add(btEditar);

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });
        pnBotoes.add(btRemover);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spItensCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
            .addComponent(pnBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spItensCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 544, 401);
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        ItemCardapio item = new ItemCardapio();
        ItemDAO id = new ItemDAO();
        CadastroItemCardapio c = new CadastroItemCardapio(this, true, item);
        
        item.setCardapio(cardapio);
        c.setVisible(true);
        
        if (c.getSalvouItem()) {
            id.inserir(item);
            listCardapio();
            initBindings();
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        int[] linhas = tbItemCardapio.getSelectedRows();
        List<ItemCardapio> lstTmpItemCardapio = new LinkedList<>();
        ItemDAO itemd = new ItemDAO();
        
        tbItemCardapio.getSelectionModel().setSelectionInterval(0, 0);  
        for (int linha : linhas) {
            int idxLista = tbItemCardapio.convertRowIndexToModel(linha);
            lstTmpItemCardapio.add(lstItemCardapio.get(idxLista));
            
        }
        itemd.excluir(lstTmpItemCardapio.get(tbItemCardapio.getSelectedRow()));
        lstItemCardapio.removeAll(lstTmpItemCardapio);

        
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if (tbItemCardapio.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um registro!");
        } else if (tbItemCardapio.getSelectedRows().length > 1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione apenas um registro!");
        } else {
            int linha = tbItemCardapio.getSelectedRow();
            int idxLista = tbItemCardapio.convertRowIndexToModel(linha);
            
            ItemCardapio itemSelecionado = lstItemCardapio.get(idxLista);
            ItemCardapio item = new ItemCardapio();
            item.setNome(itemSelecionado.getNome());
            item.setPreco(itemSelecionado.getPreco());
            item.setDescricao(itemSelecionado.getDescricao());
            item.setIdItemCardapio(itemSelecionado.getIdItemCardapio());
            
            CadastroItemCardapio c = new CadastroItemCardapio(this, true, item);
            c.setVisible(true);
               
            ItemDAO itemd = new ItemDAO();
            
            if (c.getSalvouItem()) {
                lstItemCardapio.set(idxLista, item);
                if(itemd.alterar(item))
                {
                    System.out.println("Alterou");
                }
                else
                    System.out.println("Nao Alterou");
                
            }
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btListagemPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListagemPedidosActionPerformed
        new JanelaListagemPedidos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btListagemPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemCardapio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btListagemPedidos;
    private javax.swing.JButton btRemover;
    private javax.swing.JPanel pnBotoes;
    private javax.swing.JScrollPane spItensCardapio;
    private javax.swing.JTable tbItemCardapio;
    // End of variables declaration//GEN-END:variables
}
